version: "3"
services:
  frontend2:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
    networks:
      - frontend
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend


networks:
  frontend: