services:
  pi-hole:
    build:
      context: ./pi-hole
      dockerfile: Dockerfile
    ports:
      - "8082:80"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: "changeme"
      DNS1: "cloudflared#5053"
      DNS2: "no"
    networks:
      - default
  cloudflared:
    build:
      context: ./cloudflared
      dockerfile: Dockerfile
    ports:
      - "5053:5053/udp"
    networks:
      - default
    restart: unless-stopped
  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "80:4200"
      - "49153:49153"
    networks:
      - default
    volumes:
      - ./angular-frontend/src:/usr/src/app/src
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    networks:
      - default
  mongodb:
    image: mongo:4.4
    volumes:
      - ./mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    networks:
      - default
    restart: unless-stopped

networks:
  default:

volumes:
  mongodb_data:
