services:
  pi-hole:
    build:
      context: ./pi-hole
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - frontend
  frontend2:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
      - "49153:49153"
    networks:
      - frontend
    volumes:
      - ./angular-frontend/src:/usr/src/app/src
    depends_on:
      - backend1
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
