version: "3"
services:
  pi-hole:
    build:
      context: ./pi-hole
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - frontend
  frontend2:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
      - "49153:49153"
    volumes:
      - ./angular-frontend/:/usr/src/app/
    networks:
      - frontend
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
