version: "3"
services:
  pi-hole:
    build:
      context: ./pi-hole
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: "changeme"
      DNS1: "cloudflared#5053"
      DNS2: "no"
    networks:
      - default
  cloudflared:
    build:
      context: ./cloudflared
      dockerfile: Dockerfile
    ports:
      - "5053:5053/udp"
    networks:
      - default
    restart: unless-stopped
  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
      - "49153:49153"
    networks:
      - default
    volumes:
      - ./angular-frontend/src:/usr/src/app/src
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
