version: '3'

services:
  dns-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dns-container
    ports:
      - "53:53/udp"
    volumes:
      - ./named.conf:/etc/named.conf
    command: named -c /etc/named.conf -g
    user: named
    networks:
      - dns-network

networks:
  dns-network: